### PR TITLE
Feedback should contain suggestions on fixing convention violations in PR body #11

### LINKED ISSUE #11: Feedback should contain suggestions on fixing convention violations in PR body
Current regex check can only detect if description violates the convention--it is unable to detect *how* the convention was violated.

An in-depth check can be implemented such that it runs only when the regex check fails. This check will look for specific violations, enabling the bot to provide feedback on how the convention was violated and how it can be resolved.

Since the context-specific nature of this check will make the bot less general, it should be implemented in a way that can be disabled.

### PR DESCRIPTION
**Pull request by samsontmr**
Fixes #11 

Created separate module `keyword_checker` to validate PR body. Module functionality can be extended by adding checks and feedback messages.

View bot output [here](https://github.com/samsontmr/oss-bot-testing-repo/pull/4#issuecomment-282933950)

### CODE REVIEW

**Comment by damithc** [comment]
@samsontmr get this reviewed by someone with JS expertise? I can only give feedback on the external behavior. Is there any documentation on the behavior? i.e. what it will detect and what kind of message it will post

**Comment by samsontmr** [comment]
@damithc, the method names decribe the check implemented by the function (e.g. detect<what-it-detects>), or the behaviour that the returned message corresponds to (e.g. getMessageGithubKeywordMissing). Do we need extra documentation other than this? It's quite SLAPped :P

**Comment by damithc** [comment]
> @damithc, the method names decribe the check implemented by the function (e.g. detect), or the behaviour that the returned message corresponds to (e.g. getMessageGithubKeywordMissing). Do we need extra documentation other than this? It's quite SLAPped :P

The code can only tell us what it is doing, not what is supposed to do. There should be some documentation (comments or user docs) to specify what it is supposed to do. e.g. what type of problems it is supposed to catch or what it considers to be 'correct format'. Otherwise the reviewer cannot do a proper review.

**Comment by samsontmr** [comment]
@skaty can i haz review

File: keyword_checker.js [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+function detectSpaceBetweenHashtagAndDigit(string) {
+    spaceTest = new RegExp(/[\s\S]*# \d[\s\S]*/);
+    return spaceTest.test(string);
+}
+
+/*
+* Detects if a GitHub keyword is present in argument
+* Returns true if present, false otherwise
+*/
+function detectGithubKeyword(string) {
```
Comment (damithc) [inline keyword_checker.js]: Looks like this is a boolean function but not named as a boolean.

File: keyword_checker.js [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+* Returns true if present, false otherwise
+*/
+function detectSpaceBetweenHashtagAndDigit(string) {
+    spaceTest = new RegExp(/[\s\S]*# \d[\s\S]*/);
+    return spaceTest.test(string);
+}
+
+/*
+* Detects if a GitHub keyword is present in argument
+* Returns true if present, false otherwise
```
Comment (damithc) [inline keyword_checker.js]: Can be shortened to `Returns true if the argument contains one of GitHub keywords ...`
Also, specify the keywords.

**Review by damithc — CHANGES_REQUESTED** [review]
Added a few comments in passing. Not a full review.

File: keyword_checker.js [hunk 3]
```diff
@@ -0,0 +1,70 @@
...
+    /*
+    * Scans input string for convention violations and returns feedback based on
+    * detected violations
+    * Returns a string containing the formatted feedback message
+    */
+    getFeedback: function (string) {
+        message = "";
+        
+        if (containsSpaceBetweenHashtagAndDigit(string)) {
+            console.log("Detected space between # and digit");
```
Comment (Skaty) [inline keyword_checker.js]: Just a nitpick. Wouldn't it be better to use a logging system like [Winston](https://github.com/winstonjs/winston)?

File: keyword_checker.js [hunk 4]
```diff
@@ -0,0 +1,70 @@
...
+    return spaceTest.test(string);
+}
+
+/*
+* Returns true if argument contains one of GitHub keywords:
+* Fix, Fixes, Fixed, Close, Closes, Closed, Resolve, Resolves, Resolved,
+* and their lowercase equivalents, false otherwise
+*/
+function containsGithubKeyword(string) {
+    keywordTest = new RegExp(/[\s\S]*(([F|f]ix(e[d|s])?)|([C|c]lose[d|s]?)|([R|r]esolve[d|s]?))[\s\S]*/);
```
Comment (Skaty) [inline keyword_checker.js]: Split the RegExp up like this:
```javascript
var fixedRegexPattern = '([F|f]ix(e[d|s])?)';
keywordTest = new RegExp('[\\s\\S]*(' + fixedRegexPattern + ')[\\s\\S]*');
```

Remember to escape backslashes.

File: keyword_checker.js [hunk 5]
```diff
@@ -0,0 +1,70 @@
+module.exports = {
+    /*
+    * Scans input string for convention violations and returns feedback based on
+    * detected violations
+    * Returns a string containing the formatted feedback message
+    */
+    getFeedback: function (string) {
+        message = "";
```
Comment (Skaty) [inline keyword_checker.js]: According to AirBnB's JS guidelines, single quotes `'` should be used to contain strings, not double quotes.

File: index.js [hunk 6]
```diff
@@ -93,6 +94,10 @@ function buildResponseMessage(prDetails) {
     }
     if (!isValidPullRequestBody(prDetails.body)) {
         message += '1. PR Description\n';
+        if (process.env.ENABLE_KEYWORD_CHECKER != undefined
+            && process.env.ENABLE_KEYWORD_CHECKER.toLowerCase() === "true") {
```
Comment (Skaty) [inline index.js]: Just a question: are you going to give every feature an environment variable? Why not a general `OSS_BOT_SETTINGS` that would encode settings in JSON format?

That way, you don't have to do `toLowerCase()` to check if the settings is enabled.

File: keyword_checker.js [hunk 7]
```diff
@@ -0,0 +1,70 @@
...
+        
+        return message;
+    }
+};
+
+/*
+* Returns true if argument contains an issue reference, false otherwise
+*/
+function containsIssueReference(string) {
+    referenceTest = new RegExp(/[\s\S]*#\d[\s\S]*/);
```
Comment (Skaty) [inline keyword_checker.js]: This and other RegExp-ses. Why have `[\s\S]` padding between the actual regex?

Comment (Skaty) [reply keyword_checker.js]: Also, try to extract out the actual regexp as a function. That way, you don't really repeat the code multiple times.

For instance:

```javascript
function testRegex(pattern, string) {
  tester = new RegExp(pattern);
  return tester.test(string);
}

function containsIssueReference(string) {
  return testRegex('[\\s\\S]*#\d[\\s\\S]', string);
}
```

**Review by Skaty — CHANGES_REQUESTED** [review]
Some changes requested. Nothing major so far.

General comments:

- Good practice to declare variables using `var`.
- Use two spaces, not four for indentation.

File: index.js (hunk 6 above)
Comment (samsontmr) [reply index.js]: So the JSON would be part of the repo? If it is, wouldn't updating the forks reset their settings?

I'm planning to have variables only for features that make the bot less general (e.g. checking for specific conventions is one).

File: keyword_checker.js (hunk 3 above)
Comment (samsontmr) [reply keyword_checker.js]: What's the advantage of winston over console.log?

File: keyword_checker.js (hunk 7 above)
Comment (samsontmr) [reply keyword_checker.js]: The string will potentially come in the form of
```
this is a pr.
fixes #1234
some other text.
```

File: index.js (hunk 6 above)
Comment (Skaty) [reply index.js]: No, I meant have a single environment variable that encodes a JSON object, instead of having an environment variable for every setting.

Comment (samsontmr) [reply index.js]: Oh I see, that'd definitely make things easier for me but might be a challenge for users to edit parameters though, since it'll all be on a single line. @damithc any thoughts on this?

File: keyword_checker.js (hunk 7 above)
Comment (Skaty) [reply keyword_checker.js]: I don't really see the problem here.

Comment (samsontmr) [reply keyword_checker.js]: Wouldn't the test fail without the padding?

Comment (Skaty) [reply keyword_checker.js]:
```javascript
var tester = new RegExp('#\\d');
var yourString = 'this is a pr.\nfixes #1234\nsome other text.'
tester.test(yourString);
```

This returns `true`, according to the Chrome console.

File: keyword_checker.js (hunk 3 above)
Comment (Skaty) [reply keyword_checker.js]: For starters, it allows you to log levels and metadata easily, instead of having to format it. It can also do profiling.

File: keyword_checker.js (hunk 7 above)
Comment (samsontmr) [inline keyword_checker.js]: :O interesting. Why though? Shouldn't it be false since there're characters before and after it?

File: keyword_checker.js (hunk 3 above)
Comment (samsontmr) [reply keyword_checker.js]: Hm okay, I'll look into this separately.

File: keyword_checker.js [hunk 8]
```diff
@@ -0,0 +1,76 @@
...
+    if (!containsGithubKeyword(string)) {
+      console.log('Missing GitHub keyword');
+      message += getFormattedMessage(getMessageGithubKeywordMissing());
+    }
+    
+    return message;
+  }
+};
+
+function testRegexp(pattern, string) {
```
Comment (Skaty) [inline keyword_checker.js]: Put this in a utils file so that we are able to reuse the code.

File: index.js [hunk 9]
```diff
@@ -14,85 +15,89 @@ app.set('port', (process.env.PORT || 5000));
...
-    var message =  'Hi @' + prDetails.username
-                   + ', these parts of your pull request do not appear to '
-                   + 'follow our [contributing guidelines]('
-                   + process.env.CONTRIBUTING_GUIDELINES + '):\n\n';
-    if (!isValidPullRequestTitle(prDetails.title)) {
-        message += '1. PR Title\n';
-    }
-    if (!isValidPullRequestBody(prDetails.body)) {
-        message += '1. PR Description\n';
+  var message =  'Hi @' + prDetails.username
```
Comment (Skaty) [inline index.js]: According to [6.2](https://github.com/airbnb/javascript#strings--line-length), strings should be in one line.

Also, if you use ES6, you can use something called [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals), which will make this and other strings neater.

File: keyword_checker.js [hunk 10]
```diff
@@ -0,0 +1,76 @@
...
+  return 'Issue Reference (`#<issue-number>`) missing.';
+}
+
+function getMessageSpaceBetweenHashtagAndDigit() {
+  return 'There should not be a space between the `#` and `issue-number`.';
+}
+
+function getMessageGithubKeywordMissing() {
+  return 'GitHub Keyword missing: Refer [here](https://help.github.com/articles/closing-issues-via-commit-messages/#keywords-for-closing-issues) for a list of accepted keywords.';
+}
```
Comment (Skaty) [inline keyword_checker.js]: Violates [18.5](https://github.com/airbnb/javascript#whitespace--newline-at-end)

File: index.js [hunk 11]
```diff
@@ -14,85 +15,89 @@ app.set('port', (process.env.PORT || 5000));
...
+  return isValidPullRequestTitle(prDetails.title)
+         && isValidPullRequestBody(prDetails.body);
 }
 
 function isValidPullRequestTitle(prTitle) {
-    titleTest = new RegExp(process.env.REGEX_PULL_REQ_TITLE);
-    console.log('Title being validated: ' + prTitle);
-    console.log('Regex for title: ' + process.env.REGEX_PULL_REQ_TITLE);
-    return titleTest.test(prTitle);
+  titleTest = new RegExp(process.env.REGEX_PULL_REQ_TITLE);
```
Comment (Skaty) [inline index.js]: Once you put the regex inside util, you can reuse it in this file. :)

File: index.js [hunk 12]
```diff
@@ -14,85 +15,89 @@ app.set('port', (process.env.PORT || 5000));
...
+  console.log('Received PR ' + id + ' "' + title + '" from: ' + username +
+              '\n Description: "' + body + '"');
+  return {repo : repo, id : id, title : title, body : body,
+          username : username, action : action};
 }
 
 function isPullRequestToCheck(prDetails) {
-    return prDetails.action == 'opened' || prDetails.action == 'edited' ||
-           prDetails.action == 'reopened' || prDetails.action == 'review_requested';
+  return prDetails.action == 'opened' || prDetails.action == 'edited' ||
```
Comment (Skaty) [inline index.js:55]: Only indent once, don't align.

Viz:
```javascript
return prDetails.action == 'opened' || prDetails.action == 'edited' ||
  prDetails.action == 'reopened' || prDetails.action == 'review_requested';
```

If it doesn't exceed 100 characters, do put it in a single line.

File: index.js [hunk 13]
```diff
@@ -14,85 +15,89 @@ app.set('port', (process.env.PORT || 5000));
...
-        var responseMsg = buildResponseMessage(extractedPrDetails);
-        commentOnPullRequest(extractedPrDetails.repo, extractedPrDetails.id,
-                             responseMsg);
-        console.log('Message to user: \n' + '"' + responseMsg + '"');
-    }
+  console.log('Received pull request: \n' + request.body);
+  response.send();
+  if (!isPullRequest(request)) return;
+  extractedPrDetails = extractRelevantDetails(request);
+  if (isPullRequestToCheck(extractedPrDetails) &&
```
Comment (Skaty) [inline index.js]: Avoid multi-line unless line exceeds 100 characters.

**Review by Skaty — CHANGES_REQUESTED** [review]
Some other changes requested.

**Review by Skaty — APPROVED** [review]
Looks good to me! 👍

**Comment by samsontmr** [comment]
Deployed to teammates-bot.
